[package]
name = "shark"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
crossterm = "0.28.1"
ropey = "1.6.1"
tree-sitter = "0.24.6"
tree-sitter-rust = "0.23.2"
